CUDA_VISIBLE_DEVICES=2 python detect.py \
--cfg=/data1/chenww/my_research/yolov3/cfg/yolov3-1cls.cfg  \
--names=/data1/chenww/my_research/yolov3/data/d13/small_1cls/small_1cls.names  \
--weights=/data1/chenww/my_research/yolov3/output/1cls_896_bs8_ep300_scratch_oriAnachor_yolo3ori/best.pt \
--source=/data1/chenww/my_research/yolov3/data/d13/small_1cls/images/test/  \
--output=/data1/chenww/my_research/yolov3/output/1cls_896_bs8_ep300_scratch_oriAnachor_yolo3ori/inference_test_result/  \
--img-size=896 \
--conf-thres=0.1 \
--iou-thres=0.001